version: "3.9"
services:
  app:
    build: .
    image: coffee-line-rag-bot:latest
    container_name: coffee-line-rag-bot
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

